name: Build Visual Studio Project & Release

on:
  push:
    branches:
      - build
    tags:
      - 'auto'
  workflow_dispatch:

env:
  SOLUTION_FILE: Track-O-Matic.sln

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Restore packages
        run: nuget restore ${{ env.SOLUTION_FILE }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE }} /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: '**/bin/Release/*'
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'
      - name: Restore packages
        run: dotnet restore ${{ env.SOLUTION_FILE }}
      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration release --runtime linux-x64
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-Binaries
          path: '**/bin/linux-x64/*'
  release:
    needs: [build-windows, build-linux]
    if: always()  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Windows built
        id: windows_built
        uses: actions/download-artifact@v4
        with:
          name: Windows Executable
          path: ./dist/windows
        continue-on-error: true
      - name: Download Linux built
        id: linux_built
        uses: actions/download-artifact@v4
        with:
          name: Linux Executable
          path: ./dist/linux
        continue-on-error: true
      - name: Generate tag
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"   # e.g. v2025.11.06.2019
          echo "TAG=$VERSION" >> $GITHUB_ENV
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $VERSION
          git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Github Release
        if: |
          (steps.windows_built.outcome == 'success') || 
          (steps.linux_built.outcome == 'success')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          files: |
            './dist/windows/*'
            './dist/linux/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
